# sdks/python/src/magnus/cli/_local.py
"""`magnus local <verb>` sub-commands: run a full local Magnus stack."""
import os
import sys
import subprocess
import typer
import httpx
from typing import List, Optional
from pathlib import Path
from rich.markup import escape as rich_escape
from .. import save_site
from ._shared import SignalSafeSpinner, print_error, print_msg


local_app = typer.Typer(
    name="local",
    help=(
        "Local execution mode: run Magnus jobs in Docker containers on your machine.\n\n"
        "Subcommands:\n"
        "  start     Start a local Magnus server\n"
        "  stop      Stop the local Magnus server\n"
        "  status    Show local server status\n\n"
        "This spins up a full Magnus backend + frontend using Docker instead of SLURM.\n"
        "All magnus commands (run, logs, status, etc.) work identically.\n\n"
        "Examples:\n"
        "  magnus local start\n"
        "  magnus local stop"
    ),
)
LOCAL_MAGNUS_DIR = Path.home() / ".magnus"
LOCAL_CONFIG_PATH = LOCAL_MAGNUS_DIR / "local_config.yaml"
LOCAL_DATA_DIR = LOCAL_MAGNUS_DIR / "data"
LOCAL_BACKEND_LOG = LOCAL_MAGNUS_DIR / "backend.log"
LOCAL_FRONTEND_LOG = LOCAL_MAGNUS_DIR / "frontend.log"
LOCAL_PREVIOUS_SITE_FILE = LOCAL_MAGNUS_DIR / "local_previous_site"
LOCAL_SITE_NAME = "local"
LOCAL_BACK_END_PORT = 8017
LOCAL_FRONT_END_PORT = 3011
LOCAL_OPERATION_TIMEOUT = 600  # 10 minutes; generous for slow networks / cold starts


def _generate_local_config() -> Path:
    """Generate a minimal magnus_config.yaml for local mode."""
    import secrets as _secrets
    import getpass
    # Path.as_posix() — 避免 Windows 反斜杠在 YAML 中被解释为转义字符
    root_posix = LOCAL_DATA_DIR.as_posix()
    config_content = f"""\
# Auto-generated by `magnus local start`
# Do not edit manually — regenerated on each start.

client:
  jobs:
    poll_interval: 2

server:
  address: http://127.0.0.1
  front_end_port: {LOCAL_FRONT_END_PORT}
  back_end_port: {LOCAL_BACK_END_PORT}
  root: {root_posix}
  cors_origins:
    - "*"
  database:
    pool_size: 4
    max_overflow: 8
    pool_timeout: 10
    pool_recycle: 3600
  auth:
    provider: local
    jwt_signer:
      secret_key: {_secrets.token_hex(32)}
      algorithm: HS256
      expire_minutes: 10080
  scheduler:
    heartbeat_interval: 2
    snapshot_interval: 300
  service_proxy:
    max_concurrency: 64
  file_custody:
    max_size: 10G
    max_file_size: 2G
    max_processes: 16
    default_ttl_minutes: 60
    max_ttl_minutes: 1440

execution:
  backend: local
  container_runtime: docker
  resource_cache:
    container_cache_size: 80G
    repo_cache_size: 20G

cluster:
  name: Local
  gpus: []
  max_cpu_count: 128
  max_memory_demand: 256G
  default_cpu_count: 4
  default_memory_demand: 4G
  default_runner: {getpass.getuser()}
  default_container_image: docker://pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
  default_ephemeral_storage: 10G
  default_system_entry_command: ""
"""
    LOCAL_MAGNUS_DIR.mkdir(parents=True, exist_ok=True)
    LOCAL_DATA_DIR.mkdir(parents=True, exist_ok=True)
    LOCAL_CONFIG_PATH.write_text(config_content, encoding="utf-8")
    return LOCAL_CONFIG_PATH


def _find_magnus_project_root() -> Optional[Path]:
    """
    Locate the Magnus project root directory.
    Strategy: look relative to the SDK installation, then in ~/.magnus/repository.
    """
    # Strategy 1: SDK installed from source (editable install)
    # __file__ = sdks/python/src/magnus/cli/_local.py
    # .parents[5] = magnus project root
    project_root = Path(__file__).resolve().parents[5]
    if (project_root / "back_end" / "server" / "main.py").exists():
        return project_root

    # Strategy 2: Downloaded to ~/.magnus/repository
    repo_root = LOCAL_MAGNUS_DIR / "repository"
    if (repo_root / "back_end" / "server" / "main.py").exists():
        return repo_root

    return None


def _kill_port(port: int) -> bool:
    if sys.platform == "win32":
        result = subprocess.run(
            ["netstat", "-ano", "-p", "TCP"],
            capture_output=True, text=True,
        )
        for line in result.stdout.splitlines():
            if f":{port}" in line and "LISTENING" in line:
                parts = line.split()
                try:
                    pid = int(parts[-1])
                    subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)], capture_output=True)
                    return True
                except (ValueError, IndexError):
                    continue
    else:
        # lsof works on both macOS and Linux (fuser -k syntax differs across platforms)
        try:
            result = subprocess.run(["lsof", "-ti", f":{port}"], capture_output=True, text=True)
        except FileNotFoundError:
            return False  # lsof not installed on this system
        pids = result.stdout.strip()
        if pids:
            subprocess.run(["kill", "-9"] + pids.split(), capture_output=True)
            return True
    return False


def _check_port_available(port: int) -> bool:
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        try:
            s.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def _popen_detached(cmd: List[str], **kwargs) -> subprocess.Popen:
    """Start a detached subprocess, handling cross-platform differences."""
    if sys.platform == "win32":
        kwargs["creationflags"] = subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.CREATE_NO_WINDOW
    else:
        kwargs["start_new_session"] = True
    return subprocess.Popen(cmd, **kwargs)


@local_app.command(name="start")
def local_start():
    """
    Start a local Magnus server with Docker backend.

    This generates a local config, starts the backend + frontend,
    and registers it as the current SDK site. All subsequent magnus commands
    (run, logs, status, etc.) will use this local server.

    Prerequisites: Docker and git must be installed. Node.js is optional (for Web UI).

    Examples:
      magnus local start
    """
    import shutil as _shutil
    import time

    # ── 依赖检查：一次性报告所有结果 ──
    REQUIRED_TOOLS = [
        ("docker", "Container runtime for running jobs",
         "Install Docker Desktop: https://docs.docker.com/get-docker/"),
        ("git", "Version control for repository checkout",
         "Install Git: https://git-scm.com/downloads"),
        ("uv", "Python package manager for the Magnus backend",
         "Install uv: https://docs.astral.sh/uv/getting-started/installation/"),
    ]

    all_ok = True
    print_msg("Checking dependencies...")
    for cmd, purpose, install_hint in REQUIRED_TOOLS:
        if _shutil.which(cmd) is None:
            print_msg(f"  [red]MISSING[/red]  {cmd} — {purpose}")
            print_msg(f"          {install_hint}")
            all_ok = False
        else:
            print_msg(f"  [green]OK[/green]      {cmd}")

    # Docker 特殊检查：二进制存在但 daemon 可能没启动
    if _shutil.which("docker") is not None:
        try:
            subprocess.run(["docker", "info"], capture_output=True, check=True, timeout=10)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            print_msg(f"  [red]MISSING[/red]  docker daemon — Docker is installed but not running")
            print_msg(f"          Start Docker Desktop, then try again.")
            all_ok = False

    if not all_ok:
        print_msg("")
        print_msg("Please install the missing dependencies and run 'magnus local start' again.")
        raise typer.Exit(1)

    OPTIONAL_TOOLS = [
        ("node", "JavaScript runtime for the Magnus Web UI"),
        ("ffmpeg", "Audio transcription in Explorer"),
    ]
    for cmd, purpose in OPTIONAL_TOOLS:
        if _shutil.which(cmd) is None:
            print_msg(f"  [yellow]OPTIONAL[/yellow]  {cmd} — {purpose}")

    # 端口冲突检测
    ports_ok = True
    for port, role in [(LOCAL_BACK_END_PORT, "backend"), (LOCAL_FRONT_END_PORT, "frontend")]:
        if not _check_port_available(port):
            print_msg(f"  [red]OCCUPIED[/red]  port {port} ({role})")
            ports_ok = False
    if not ports_ok:
        print_msg("")
        print_msg("Free the occupied port(s) and retry.")
        raise typer.Exit(1)

    print_msg("")

    # Find project root (auto-clone if not found)
    project_root = _find_magnus_project_root()
    if project_root is None:
        repo_target = LOCAL_MAGNUS_DIR / "repository"
        print_msg("Magnus project not found. Cloning into ~/.magnus/repository ...")
        clone_result = subprocess.run(
            ["git", "clone", "https://github.com/rise-agi/magnus.git", str(repo_target)],
            capture_output=True,
            text=True,
            timeout=LOCAL_OPERATION_TIMEOUT,
        )
        if clone_result.returncode != 0:
            print_error(f"git clone failed:\n{clone_result.stderr}")
            raise typer.Exit(1)
        project_root = repo_target
        if not (project_root / "back_end" / "server" / "main.py").exists():
            print_error(f"Cloned repository at {repo_target} does not contain a valid Magnus project.")
            raise typer.Exit(1)
        print_msg(f"Cloned Magnus to {rich_escape(str(repo_target))}")

    back_end_path = project_root / "back_end"
    front_end_path = project_root / "front_end"

    # Generate config
    config_path = _generate_local_config()
    print_msg(f"Config generated: {rich_escape(str(config_path))}")

    # Save previous SDK site for restore on stop
    from ..config import _load_config
    sdk_config = _load_config()
    previous_site = sdk_config.get("current")
    if previous_site and previous_site != LOCAL_SITE_NAME:
        LOCAL_PREVIOUS_SITE_FILE.write_text(previous_site, encoding="utf-8")

    # Start backend server (uv run 使用后端自己的 venv，而非 SDK 的 Python)
    # uv sync — 先在前台安装依赖，让用户看到进度（类似 npm install）
    if not (back_end_path / ".venv").exists():
        print_msg("Installing backend dependencies...")
        sync_result = subprocess.run(
            ["uv", "sync"],
            cwd=str(back_end_path),
            timeout=LOCAL_OPERATION_TIMEOUT,
        )
        if sync_result.returncode != 0:
            print_error("uv sync failed (see output above)")
            raise typer.Exit(1)

    print_msg("Starting backend server...")
    # Redirect to a log file instead of PIPE — a PIPE with no reader would
    # fill its buffer and block the detached process indefinitely.
    log_handle = open(LOCAL_BACKEND_LOG, "w")
    backend_proc = _popen_detached(
        ["uv", "run", "-m", "server.main", "--deliver", "--config", str(config_path)],
        cwd=str(back_end_path),
        stdout=log_handle,
        stderr=log_handle,
    )
    log_handle.close()  # child inherited the fd; parent can release

    # Wait for backend to be fully ready (lifespan complete, API serving)
    health_url = f"http://127.0.0.1:{LOCAL_BACK_END_PORT}/health"
    ready_deadline = time.time() + LOCAL_OPERATION_TIMEOUT
    backend_ready = False
    with SignalSafeSpinner("[magnus.prefix][Magnus][/magnus.prefix] Waiting for backend..."):
        while time.time() < ready_deadline:
            if backend_proc.poll() is not None:
                break
            try:
                r = httpx.get(health_url, timeout=2)
                if r.status_code == 200:
                    backend_ready = True
                    break
            except (httpx.ConnectError, httpx.TimeoutException):
                pass
            time.sleep(0.5)

    if backend_proc.poll() is not None and not backend_ready:
        stderr_output = LOCAL_BACKEND_LOG.read_text(encoding="utf-8", errors="replace").strip()
        error_detail = f":\n{stderr_output}" if stderr_output else f" (check {LOCAL_BACKEND_LOG})"
        print_error(f"Backend failed to start{error_detail}")
        raise typer.Exit(1)

    if not backend_ready:
        # Kill the detached backend to prevent port leak on next start
        try:
            backend_proc.terminate()
            backend_proc.wait(timeout=5)
        except (subprocess.TimeoutExpired, OSError):
            try:
                backend_proc.kill()
            except OSError:
                pass
        _kill_port(LOCAL_BACK_END_PORT)
        print_error(f"Backend did not become ready within {LOCAL_OPERATION_TIMEOUT}s (check {LOCAL_BACKEND_LOG})")
        raise typer.Exit(1)

    print_msg(f"Backend started at http://127.0.0.1:{LOCAL_BACK_END_PORT}")

    # Start frontend
    npm_cmd = "npm.cmd" if sys.platform == "win32" else "npm"
    npx_cmd = "npx.cmd" if sys.platform == "win32" else "npx"
    frontend_started = False

    if front_end_path.exists() and (front_end_path / "package.json").exists():
        frontend_env = os.environ.copy()
        frontend_env["MAGNUS_CONFIG_PATH"] = str(config_path)
        frontend_env["MAGNUS_DELIVER"] = "TRUE"

        # npm install — 输出直接流到终端，让用户看到进度
        if not (front_end_path / "node_modules").exists():
            print_msg("Installing frontend dependencies...")
            install_result = subprocess.run(
                [npm_cmd, "install"],
                cwd=str(front_end_path),
                timeout=LOCAL_OPERATION_TIMEOUT,
            )
            if install_result.returncode != 0:
                print_error("npm install failed (see output above)")
                raise typer.Exit(1)

        # next build — 只在 .next 不存在时执行
        next_dir = front_end_path / ".next"
        if not next_dir.exists():
            print_msg("Building frontend (first time)...")
            build_result = subprocess.run(
                [npx_cmd, "next", "build"],
                cwd=str(front_end_path),
                env=frontend_env,
                timeout=LOCAL_OPERATION_TIMEOUT,
            )
            if build_result.returncode != 0:
                print_error("next build failed (see output above)")
                raise typer.Exit(1)

        # npm run start → server.mjs (Next.js + WS proxy)，生产模式，日志写文件
        print_msg("Starting frontend...")
        fe_log = open(LOCAL_FRONTEND_LOG, "w")
        frontend_proc = _popen_detached(
            [npm_cmd, "run", "start", "--", "-p", str(LOCAL_FRONT_END_PORT)],
            cwd=str(front_end_path),
            stdout=fe_log,
            stderr=fe_log,
            env=frontend_env,
        )
        fe_log.close()
        fe_deadline = time.time() + LOCAL_OPERATION_TIMEOUT
        with SignalSafeSpinner("[magnus.prefix][Magnus][/magnus.prefix] Waiting for frontend..."):
            while time.time() < fe_deadline:
                if frontend_proc.poll() is not None:
                    break
                try:
                    httpx.get(f"http://127.0.0.1:{LOCAL_FRONT_END_PORT}", timeout=2)
                    frontend_started = True
                    break
                except (httpx.ConnectError, httpx.TimeoutException):
                    pass
                time.sleep(0.5)
        if frontend_started:
            print_msg(f"Frontend started at http://127.0.0.1:{LOCAL_FRONT_END_PORT}")
        else:
            fe_err = LOCAL_FRONTEND_LOG.read_text(encoding="utf-8", errors="replace").strip()
            print_msg(f"Warning: Frontend failed to start within {LOCAL_OPERATION_TIMEOUT}s (check {LOCAL_FRONTEND_LOG})")
            if fe_err:
                print_msg(fe_err[:500])

    # Register as SDK site
    local_address = f"http://127.0.0.1:{LOCAL_BACK_END_PORT}"
    save_site(LOCAL_SITE_NAME, local_address, "local")
    print_msg(f"Site '{LOCAL_SITE_NAME}' registered and set as current.")

    # Register bundled blueprints
    from ..bundled.register import register_bundled_blueprints, register_bundled_skills
    with SignalSafeSpinner("[magnus.prefix][Magnus][/magnus.prefix] Registering bundled blueprints..."):
        registered = register_bundled_blueprints(local_address, "local")
    if registered:
        print_msg(f"Registered {len(registered)} bundled blueprint(s):")
        for bp_id, bp_title in registered:
            print_msg(f"  - {rich_escape(str(bp_title))} ({rich_escape(str(bp_id))})")

    # Register bundled skills
    with SignalSafeSpinner("[magnus.prefix][Magnus][/magnus.prefix] Registering bundled skills..."):
        registered_skills = register_bundled_skills(local_address, "local")
    if registered_skills:
        print_msg(f"Registered {len(registered_skills)} bundled skill(s):")
        for sk_id, sk_title in registered_skills:
            print_msg(f"  - {rich_escape(str(sk_title))} ({rich_escape(str(sk_id))})")

    print_msg("")
    if frontend_started:
        print_msg(f"Open http://127.0.0.1:{LOCAL_FRONT_END_PORT} in your browser, or use the CLI:")
    else:
        print_msg("Use the CLI:")
    print_msg("  magnus --help            # see all available commands")
    print_msg("  magnus local stop        # stop the server")


@local_app.command(name="stop")
def local_stop():
    """
    Stop the local Magnus server and frontend.

    Examples:
      magnus local stop
    """
    import time
    stopped_any = False

    for port, role in [(LOCAL_FRONT_END_PORT, "Frontend"), (LOCAL_BACK_END_PORT, "Backend")]:
        if not _check_port_available(port):
            _kill_port(port)
            time.sleep(0.5)
            if _check_port_available(port):
                print_msg(f"{role} stopped (port {port})")
            else:
                print_msg(f"[yellow]Warning[/yellow]: Failed to stop {role} on port {port}. Kill it manually.")
            stopped_any = True

    if not stopped_any:
        print_msg("No local server running.")

    # Restore previous SDK site
    if LOCAL_PREVIOUS_SITE_FILE.exists():
        previous_site = LOCAL_PREVIOUS_SITE_FILE.read_text(encoding="utf-8").strip()
        if previous_site:
            from ..config import set_current_site
            set_current_site(previous_site)
            print_msg(f"Restored SDK site to '{rich_escape(previous_site)}'.")
        LOCAL_PREVIOUS_SITE_FILE.unlink(missing_ok=True)


@local_app.command(name="status")
def local_status():
    """
    Show local server status.

    Examples:
      magnus local status
    """
    any_alive = False

    if not _check_port_available(LOCAL_BACK_END_PORT):
        print_msg(f"Backend running at http://127.0.0.1:{LOCAL_BACK_END_PORT}")
        any_alive = True

    if not _check_port_available(LOCAL_FRONT_END_PORT):
        print_msg(f"Frontend running at http://127.0.0.1:{LOCAL_FRONT_END_PORT}")
        any_alive = True

    if not any_alive:
        print_msg("No local server running.")
