# back_end/python_scripts/magnus_slurm.py
import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

def log_cloud_only(msg: str):
    """
    辅助函数：只打印到标准输出（给 Magnus 云端看），不写入用户文件。
    使用 flush 确保云端日志实时性。
    """
    sys.stdout.write(f"{msg}\n")
    sys.stdout.flush()

def main():
    parser = argparse.ArgumentParser(description="Magnus SLURM Proxy Executor")
    parser.add_argument("--working-directory", required=True, help="Job working directory")
    parser.add_argument("--slurm-script", required=True, help="Content of the shell script to run")
    parser.add_argument("--conda-environment", required=True, help="Conda environment to activate")
    parser.add_argument("--output-path", default="", help="Optional path to redirect stdout/stderr")
    
    args = parser.parse_args()

    # 1. 准备工作目录
    work_dir = Path(args.working_directory).expanduser().resolve()
    log_cloud_only(f"[Magnus] Setting up working directory: {work_dir}")
    os.makedirs(work_dir, exist_ok=True)

    # 2. 生成临时包装脚本
    # 注意：这里我们回退到了最基础的 Conda 处理逻辑，不做额外魔改
    temp_script = tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.sh', prefix='magnus_runner_')
    script_path = Path(temp_script.name)
    
    try:
        wrapper_content = f"""#!/bin/bash
# --- Auto-generated by Magnus Platform ---

# A. Initialize Conda
if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/miniconda3/etc/profile.d/conda.sh"
elif [ -f "/opt/miniconda3/etc/profile.d/conda.sh" ]; then
    source "/opt/miniconda3/etc/profile.d/conda.sh"
elif [ -f "$HOME/anaconda3/etc/profile.d/conda.sh" ]; then
    source "$HOME/anaconda3/etc/profile.d/conda.sh"
else
    CONDA_BASE=$(conda info --base 2>/dev/null)
    if [ -n "$CONDA_BASE" ]; then
        source "$CONDA_BASE/etc/profile.d/conda.sh"
    fi
fi

# B. Activate Environment
# 注意：这里的 echo 会被 Python 捕获，我们在 Python 层过滤它，不让它进用户日志文件
echo "[Magnus] Activating Conda environment: {args.conda_environment}"
conda activate {args.conda_environment} || {{ echo "[Magnus] Error: Failed to activate environment '{args.conda_environment}'"; exit 1; }}

# C. Execute User Script
echo "[Magnus] Starting user script execution..."
echo "---------------------------------------------------"
set -e
{args.slurm_script}
"""
        temp_script.write(wrapper_content)
        temp_script.close()
        script_path.chmod(0o755)

        # 3. 确定本地日志路径
        if args.output_path:
            out_path = Path(args.output_path).expanduser()
            if not out_path.is_absolute():
                out_path = work_dir / out_path
        else:
            job_id = os.environ.get("SLURM_JOB_ID", "local")
            out_path = work_dir / f"slurm-{job_id}.out"

        out_path.parent.mkdir(parents=True, exist_ok=True)
        log_cloud_only(f"[Magnus] Redirecting user output to: {out_path}")

        # 4. 执行脚本 (Stream Processing + Filtering)
        cmd = ["bash", str(script_path)]
        
        # 打开文件准备写入 ('w' 模式，保证文件从头开始是纯净的)
        with open(out_path, "w", encoding="utf-8") as outfile:
            process = subprocess.Popen(
                cmd, 
                cwd=work_dir, 
                stdout=subprocess.PIPE, 
                stderr=subprocess.STDOUT, # 将用户的 stderr 合并进 stdout
                text=True, 
                bufsize=1 # 行缓冲
            )
            
            assert process.stdout is not None
            
            for line in process.stdout:
                # === 核心逻辑：净化过滤器 ===
                # 检查这行是不是 Magnus 的控制信息
                # 如果是，只发给云端 (sys.stdout)，不写入文件 (outfile)
                if line.startswith("[Magnus]") or line.startswith("---------------------------------------------------"):
                    sys.stdout.write(line)
                    sys.stdout.flush()
                else:
                    # 如果是用户的真实输出
                    # 1. 写入本地文件
                    outfile.write(line)
                    outfile.flush()
                    # 2. 同时发给云端
                    sys.stdout.write(line)
                    sys.stdout.flush()

            return_code = process.wait()

        # 5. 检查结果
        if return_code != 0:
            log_cloud_only(f"[Magnus] Job failed with exit code: {return_code}")
            sys.exit(return_code)
        
        log_cloud_only(f"[Magnus] Job completed successfully.")

    except Exception as e:
        log_cloud_only(f"[Magnus] Critical Error: {str(e)}")
        sys.exit(1)
        
    finally:
        # 6. 清理
        if script_path.exists():
            try:
                os.remove(script_path)
            except OSError:
                pass

if __name__ == "__main__":
    main()